spring:
  datasource:
    url: jdbc:mysql://localhost:3306/smartbox?serverTimezone=UTC
    username: root
    password: # (Add your password here if needed)
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
server:
  port: 8091
