server:
  port: 8765  # Port on which the API Gateway will run

spring:
  application:
    name: gateway-service  # Name of the application

  config:
    import: optional:configserver:http://localhost:8888  # Optional Config Server URL

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true  # Enable service discovery for routing
